//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word_Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Word_Generator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word Generator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string AppNameHelp {
            get {
                return ResourceManager.GetString("AppNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add placeholder.
        /// </summary>
        public static string BtnAddPlaceholder {
            get {
                return ResourceManager.GetString("BtnAddPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate document.
        /// </summary>
        public static string BtnGenerate {
            get {
                return ResourceManager.GetString("BtnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string BtnHelp {
            get {
                return ResourceManager.GetString("BtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove placeholder.
        /// </summary>
        public static string BtnRemovePlaceholder {
            get {
                return ResourceManager.GetString("BtnRemovePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Excel.
        /// </summary>
        public static string BtnSelectExcel {
            get {
                return ResourceManager.GetString("BtnSelectExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open folder for files.
        /// </summary>
        public static string BtnSelectOutput {
            get {
                return ResourceManager.GetString("BtnSelectOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a Word template.
        /// </summary>
        public static string BtnSelectWord {
            get {
                return ResourceManager.GetString("BtnSelectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic file numbering.
        /// </summary>
        public static string ChkAutoNumber {
            get {
                return ResourceManager.GetString("ChkAutoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column Excel.
        /// </summary>
        public static string ColumnExcel {
            get {
                return ResourceManager.GetString("ColumnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author&apos;s email: .
        /// </summary>
        public static string EmailAuthor {
            get {
                return ResourceManager.GetString("EmailAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error converting .doc -&gt; .docx: .
        /// </summary>
        public static string ErrorConvert {
            get {
                return ResourceManager.GetString("ErrorConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading Excel: .
        /// </summary>
        public static string ErrorExcel {
            get {
                return ResourceManager.GetString("ErrorExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select all files and folder for output!.
        /// </summary>
        public static string ErrorSelectFiles {
            get {
                return ResourceManager.GetString("ErrorSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HOW TO WORK WITH THE PROGRAM?
        ///
        ///1. Select a Word template (.doc, .docx) that contains placeholders, for example:
        ///{{NAME}}, {{INV_NUM}}, {{YEAR}}
        ///The program will take the formatting of these elements (font, size, etc.)
        ///
        ///2. Select an Excel file with the data you want to insert into the template
        ///
        ///3. In the left column, write the name of the placeholder from the template, and in the right column, select the corresponding column from the Excel table
        ///
        ///4. Select the folder where all documents will be sav [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string HelpWindowText {
            get {
                return ResourceManager.GetString("HelpWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Placeholders in Word.
        /// </summary>
        public static string PlaceholderInWord {
            get {
                return ResourceManager.GetString("PlaceholderInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Placeholders and corresponding Excel columns: .
        /// </summary>
        public static string PlaceholdersGrid {
            get {
                return ResourceManager.GetString("PlaceholdersGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email copied to clipboard!.
        /// </summary>
        public static string TxtEmailCopy {
            get {
                return ResourceManager.GetString("TxtEmailCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate complete!.
        /// </summary>
        public static string TxtFinishGenerate {
            get {
                return ResourceManager.GetString("TxtFinishGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document created: .
        /// </summary>
        public static string TxtLogCreateDoc {
            get {
                return ResourceManager.GetString("TxtLogCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An update is available! Update the app?.
        /// </summary>
        public static string UpdaterText {
            get {
                return ResourceManager.GetString("UpdaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check updates.
        /// </summary>
        public static string UpdaterTitle {
            get {
                return ResourceManager.GetString("UpdaterTitle", resourceCulture);
            }
        }
    }
}
